# Generated by Django 2.2.4 on 2019-08-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FILE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfileform',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
