# Generated by Django 2.2.4 on 2019-08-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(max_length=100, unique=True, verbose_name='Ubicacion')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Head(Player)',
                'verbose_name_plural': 'Heads(Player)',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_despublicacion', models.DateField()),
                ('priority', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('lunes_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('lunes_fin', models.TimeField(blank=True, default=None, null=True)),
                ('martes_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('martes_fin', models.TimeField(blank=True, default=None, null=True)),
                ('miercoles_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('miercoles_fin', models.TimeField(blank=True, default=None, null=True)),
                ('jueves_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('jueves_fin', models.TimeField(blank=True, default=None, null=True)),
                ('viernes_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('viernes_fin', models.TimeField(blank=True, default=None, null=True)),
                ('sabado_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('sabado_fin', models.TimeField(blank=True, default=None, null=True)),
                ('domingo_inicio', models.TimeField(blank=True, default=None, null=True)),
                ('domingo_fin', models.TimeField(blank=True, default=None, null=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Head')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
