# Generated by Django 2.2.4 on 2019-08-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='file',
            field=models.FileField(default=1, upload_to='Hidra'),
            preserve_default=False,
        ),
    ]
