# Generated by Django 2.2.4 on 2019-08-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_config_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='Hidra'),
        ),
    ]
