# Generated by Django 2.2.4 on 2019-08-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190815_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Hidra'),
        ),
    ]
